# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleAuthTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for googleAuthTest
  pod 'GoogleSignIn'

  target 'googleAuthTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'googleAuthTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end